### ISSUE TITLE
Headless hardware controller accesable over the network

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/pigg#106]
This could be "pigglet" binary, that is compiled without any UI.

It will need a network method to interact with the UI (piggui).

Piggui, will need to have a selector to interact with the local hardware, or connect to a pigglet on remote hardware, with the network connections and security in place.

Pigglet will need to be able to be started with some credentials or similar, that piggui uses to authenticate to it.

Maybe piggui can detect Pis on the local network (using nmap, or mDNS?) and then detect if it has a pigglet service running on it to connect to.

**Comment by andrewdavidmackenzie** [comment]
Investigate iroh as a possible way to make easy connections between GUI and Pi with GPIO Hardware 

https://iroh.computer/docs/layers/networking

**Comment by andrewdavidmackenzie** [comment]
In order to complete this, we will need:
- [ ] https://github.com/andrewdavidmackenzie/pigg/issues/221 
- [ ] https://github.com/andrewdavidmackenzie/pigg/issues/222

**Comment by andrewdavidmackenzie** [comment]
https://github.com/andrewdavidmackenzie/pigg/pull/214/ makes substantial progress on this for iroh-net connecting.

Things remaining to be done:
- [ ] Finish capturing updates to input levels in network_subscription.rs
- [ ] Simplify data required in GUI down to node id and optional relay.
- [ ] Allow piglet to be started as a system service - https://github.com/andrewdavidmackenzie/pigg/issues/224
- [ ] UI additions https://github.com/andrewdavidmackenzie/pigg/issues/222 and https://github.com/andrewdavidmackenzie/pigg/issues/221
- [ ] Wire up the UI elements and create hardware_subscription or network_subscription according to features and state ot networking
- [ ] discovery of Pis on local net https://github.com/andrewdavidmackenzie/pigg/issues/223

**Comment by andrewdavidmackenzie** [comment]
We have all the bits now, we just need the dialog, connect things up, handle some error cases, maybe tweak the display of status... That will be enough work, so I delayed discovery issue to a later release.
@sundaram123krishnan

**Comment by andrewdavidmackenzie** [comment]
With https://github.com/andrewdavidmackenzie/pigg/pull/260 merged this is largely complete and working
We have added a number of other polishing issues, but it's basically done - so closing this! Yeh!
