### ISSUE TITLE
Release 0.2.0 plan

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/pigg#142]
I propose that release 0.2.0 be mainly a code and UI polishing and clean-up release, with maybe one new visible feature that users would care about.

Code Cleanup issues:
- [x] [Tracker issue for completing error/status handling](#89)
- [x] Some refactoring and code clean-up
- [x] Increase tests and coverage

UI Polishing:
- [x] Pi Layout issues
- [x] [Load/Save niceties](#103)
- [x] [Respond to message to go FullScreen from Window Manager](#69)
- [x] [Responsive layout and top-window size](#141)

Feature issues:
- [x] [Waveform widget to display inputs value over time](#116)

The Release itself
- [x] [video showing UI and Hardware side-by-side](#120) - I wanted to do this for 0.1.0 but have struggled with screencast recording on my Pi400
- [x] Update readme text and add waveform gif
- [x] Update version in Cargo.toml
- [x] Create a tag
- [x] Publish to crates.io
- [x] Test installing from crates.io and running - on:
   - [x] mac
   - [x] linux
   - [x] pi
- [x] Create release in GitHub with release notes, add text and gifs [done here](https://github.com/andrewdavidmackenzie/pigg/releases/tag/0.2.0)

Communicating the Release
- [x] Mention in reddit for pi
- [x] Mention in reddit for rust
- [x] Mention in pi forums (pending approval by moderator)
- [x] Mention in iced discord showcase
- [x] Mention in rust-lang discord showcase
- [x] Send a PR to This Week in Rust, with a longer description this time
- [x] Send to this week in embedded rust
- [x] Let rppal author know I reviewed pin definition against Pi4 BCM2711 datasheet

**Comment by andrewdavidmackenzie** [comment]
All done.
